version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - "3800:3800"
    environment:
      PORT: ${PORT}
      BACKEND_URL: ${BACKEND_URL}
      TOKEN_PRIVATEKEY: ${TOKEN_PRIVATEKEY}
      TOKEN_EXPIRES_IN: ${TOKEN_EXPIRES_IN}
